package trace

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/wlame/rx-go/pkg/rxtypes"
)

// TestComputePatternsHash_PythonParity pins the exact SHA256-16 output
// Python produces for a curated set of (patterns, flags) inputs. These
// hashes were generated by running the Python equivalent at the time
// of the M3 port and baked in — when they drift, either Python's
// json.dumps or our JSON builder changed, and we need to fix it.
func TestComputePatternsHash_PythonParity(t *testing.T) {
	cases := []struct {
		name     string
		patterns []string
		flags    []string
		want     string
	}{
		{
			name:     "empty_inputs",
			patterns: nil,
			flags:    nil,
			want:     "07ddcf7d90fb9d20",
		},
		{
			name:     "single_pattern_no_flags",
			patterns: []string{"error"},
			flags:    nil,
			want:     "164b5fd59c4c67a3",
		},
		{
			name:     "pattern_plus_ignore_case",
			patterns: []string{"error"},
			flags:    []string{"-i"},
			want:     "a9b9b19054a58e17",
		},
		{
			name:     "two_patterns_two_flags",
			patterns: []string{"foo", "bar"},
			flags:    []string{"-i", "-F"},
			want:     "338f138ac38e487b",
		},
		{
			name:     "patterns_with_quotes_and_backslash",
			patterns: []string{`a"b`, `c\d`},
			flags:    []string{"-w"},
			want:     "479d5bee570cc497",
		},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			got := ComputePatternsHash(tc.patterns, tc.flags)
			if got != tc.want {
				t.Errorf("ComputePatternsHash(%v, %v) = %q, want %q",
					tc.patterns, tc.flags, got, tc.want)
			}
		})
	}
}

// TestComputePatternsHash_IgnoresNonMatchingFlags confirms that flags
// outside the MATCHING_FLAGS set don't affect the hash.
func TestComputePatternsHash_IgnoresNonMatchingFlags(t *testing.T) {
	h1 := ComputePatternsHash([]string{"foo"}, nil)
	h2 := ComputePatternsHash([]string{"foo"}, []string{"--max-columns=100", "-u"})
	if h1 != h2 {
		t.Errorf("non-matching flags changed hash: %s vs %s", h1, h2)
	}
}

// TestComputePatternsHash_PatternOrderInsensitive confirms the sort
// on the input patterns before hashing.
func TestComputePatternsHash_PatternOrderInsensitive(t *testing.T) {
	h1 := ComputePatternsHash([]string{"b", "a"}, nil)
	h2 := ComputePatternsHash([]string{"a", "b"}, nil)
	if h1 != h2 {
		t.Errorf("pattern order changed hash: %s vs %s", h1, h2)
	}
}

// TestCachePath_SchemeMatchesPython confirms the layout structure.
// Expected path:
//
//	<cache_base>/trace_cache/<patterns_hash>/<path_hash>_<basename>.json
func TestCachePath_SchemeMatchesPython(t *testing.T) {
	t.Setenv("RX_CACHE_DIR", t.TempDir())
	p := CachePath("/var/log/app.log", []string{"error"}, []string{"-i"})

	dir := filepath.Dir(p)                       // .../trace_cache/<hash>
	file := filepath.Base(p)                     // <path_hash>_app.log.json
	patternsHashSeg := filepath.Base(dir)        // <hash>
	traceSeg := filepath.Base(filepath.Dir(dir)) // trace_cache

	if !filepath.IsAbs(p) {
		t.Errorf("path not absolute: %q", p)
	}
	if traceSeg != "trace_cache" {
		t.Errorf("missing trace_cache segment: %q", p)
	}
	// patterns_hash for (["error"], ["-i"]) is a9b9b19054a58e17.
	if patternsHashSeg != "a9b9b19054a58e17" {
		t.Errorf("patterns_hash segment = %q, want a9b9b19054a58e17", patternsHashSeg)
	}
	if !strings.HasSuffix(file, "_app.log.json") {
		t.Errorf("basename %q doesn't have expected suffix _app.log.json", file)
	}
}

// TestSaveAndLoadCache_RoundTrip verifies Save → Load byte-equivalence
// for the JSON shape we persist.
func TestSaveAndLoadCache_RoundTrip(t *testing.T) {
	t.Setenv("RX_CACHE_DIR", t.TempDir())
	// Create a source file so BuildCache has valid mtime/size.
	srcPath := filepath.Join(t.TempDir(), "src.log")
	if err := os.WriteFile(srcPath, []byte("hello\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	patterns := []string{"hello"}
	flags := []string{"-i"}
	matches := []rxtypes.Match{
		{
			Pattern:            "p1",
			File:               "f1",
			Offset:             0,
			RelativeLineNumber: ptrIntT(1),
			AbsoluteLineNumber: 1,
			LineText:           strPtr("hello"),
			Submatches: []rxtypes.Submatch{
				{Text: "hello", Start: 0, End: 5},
			},
		},
	}

	data, err := BuildCache(srcPath, patterns, flags, matches, nil, "")
	if err != nil {
		t.Fatalf("BuildCache: %v", err)
	}
	cp := CachePath(srcPath, patterns, flags)
	if err := SaveCache(cp, data); err != nil {
		t.Fatalf("SaveCache: %v", err)
	}
	loaded, err := LoadCache(cp)
	if err != nil {
		t.Fatalf("LoadCache: %v", err)
	}
	if loaded.PatternsHash != data.PatternsHash {
		t.Errorf("patterns_hash differs after round trip")
	}
	if len(loaded.Matches) != 1 {
		t.Fatalf("matches len = %d, want 1", len(loaded.Matches))
	}
	if loaded.Matches[0].PatternIndex != 0 {
		t.Errorf("PatternIndex = %d, want 0", loaded.Matches[0].PatternIndex)
	}
}

// TestLoadCache_WrongVersion treats version drift as a miss.
func TestLoadCache_WrongVersion(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, "cache.json")
	bad := rxtypes.TraceCacheData{Version: 999}
	body, _ := json.Marshal(bad)
	if err := os.WriteFile(p, body, 0o644); err != nil {
		t.Fatal(err)
	}
	_, err := LoadCache(p)
	if !errors.Is(err, ErrCacheMiss) {
		t.Errorf("want ErrCacheMiss on version drift, got %v", err)
	}
}

func TestLoadCache_NotFound(t *testing.T) {
	_, err := LoadCache(filepath.Join(t.TempDir(), "nonexistent.json"))
	if !errors.Is(err, ErrCacheMiss) {
		t.Errorf("want ErrCacheMiss on missing file, got %v", err)
	}
}

// TestIsCacheValid_DetectsMtimeDrift builds a cache, modifies the
// source, and confirms validity fails.
func TestIsCacheValid_DetectsMtimeDrift(t *testing.T) {
	t.Setenv("RX_CACHE_DIR", t.TempDir())
	srcPath := filepath.Join(t.TempDir(), "src.log")
	if err := os.WriteFile(srcPath, []byte("hello"), 0o644); err != nil {
		t.Fatal(err)
	}
	patterns := []string{"hello"}
	data, err := BuildCache(srcPath, patterns, nil, nil, nil, "")
	if err != nil {
		t.Fatal(err)
	}
	cp := CachePath(srcPath, patterns, nil)
	if err := SaveCache(cp, data); err != nil {
		t.Fatal(err)
	}
	if !IsCacheValid(cp, srcPath, patterns, nil) {
		t.Fatal("initially cache should be valid")
	}
	// Touch the source — mtime changes, so cache invalidates.
	if err := os.WriteFile(srcPath, []byte("hello modified"), 0o644); err != nil {
		t.Fatal(err)
	}
	if IsCacheValid(cp, srcPath, patterns, nil) {
		t.Error("cache should be invalid after source mtime changes")
	}
}

// TestShouldCache_Thresholds exercises the size + completion matrix.
func TestShouldCache_Thresholds(t *testing.T) {
	t.Setenv("RX_LARGE_FILE_MB", "50")
	cases := []struct {
		name       string
		size       int64
		maxResults *int
		completed  bool
		compressed bool
		want       bool
	}{
		{"large_complete_regular", 100 * 1024 * 1024, nil, true, false, true},
		{"small_complete_regular", 10 * 1024 * 1024, nil, true, false, false},
		{"large_incomplete_regular", 100 * 1024 * 1024, nil, false, false, false},
		{"max_results_prevents", 100 * 1024 * 1024, ptrIntT(10), true, false, false},
		{"compressed_uses_1MB_threshold", 2 * 1024 * 1024, nil, true, true, true},
		{"compressed_below_1MB", 500 * 1024, nil, true, true, false},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			got := ShouldCache(tc.size, tc.maxResults, tc.completed, tc.compressed)
			if got != tc.want {
				t.Errorf("ShouldCache(%d, %v, %v, %v) = %v, want %v",
					tc.size, tc.maxResults, tc.completed, tc.compressed, got, tc.want)
			}
		})
	}
}

// ============================================================================
// Helpers
// ============================================================================

// ptrIntT returns a pointer to an int literal — handy for building
// test match data.
func ptrIntT(v int) *int { return &v }

// strPtr returns a pointer to a string literal.
func strPtr(s string) *string { return &s }
